#!/usr/bin/env node
import { stdin, stdout } from 'node:process';
import { compile, structuredDiagnostics, analyzeContracts } from './index.js';

const documents=new Map();let buffer=Buffer.alloc(0);
stdin.on('data',(chunk)=>{buffer=Buffer.concat([buffer,chunk]);drain();});
function drain(){while(true){const marker=buffer.indexOf('\r\n\r\n');if(marker<0)return;const header=buffer.subarray(0,marker).toString('utf8');const match=/Content-Length:\s*(\d+)/i.exec(header);if(!match)throw new Error('missing Content-Length');const length=Number(match[1]);if(buffer.length<marker+4+length)return;const body=buffer.subarray(marker+4,marker+4+length).toString('utf8');buffer=buffer.subarray(marker+4+length);handle(JSON.parse(body));}}
function send(message){const json=JSON.stringify(message);stdout.write(`Content-Length: ${Buffer.byteLength(json)}\r\n\r\n${json}`);}
function response(id,result){send({jsonrpc:'2.0',id,result});}
function notify(method,params){send({jsonrpc:'2.0',method,params});}
function diagnostics(uri,text){const compiled=compile(text,{file:uri});const base=structuredDiagnostics(compiled).map((d)=>toLspDiagnostic(d,text));const contracts=analyzeContracts(text,{file:uri}).diagnostics.map((d)=>({range:{start:toLspPosition(d.span.start),end:toLspPosition(d.span.end)},severity:1,code:d.code,source:'nova',message:d.message}));return[...base,...contracts];}
function toLspDiagnostic(d,text){const start=d.start??{line:1,column:1};const end=d.end??start;return{range:{start:toLspPosition(start),end:toLspPosition(end)},severity:d.severity==='warning'?2:1,code:d.code,source:'nova',message:d.message};}
function toLspPosition(position){return{line:Math.max(0,(position.line??1)-1),character:Math.max(0,(position.column??1)-1)};}
function symbols(uri,text){const contracts=analyzeContracts(text,{file:uri});return Object.values(contracts.functions).map((fn)=>({name:fn.name,kind:12,range:{start:toLspPosition(fn.span.start),end:toLspPosition(fn.span.end)},selectionRange:{start:toLspPosition(fn.span.start),end:toLspPosition(fn.span.start)},detail:`${fn.async?'async ':''}fn effects=${fn.effects.join(',')||'none'}`}));}
function handle(message){const {id,method,params={}}=message;if(method==='initialize')return response(id,{capabilities:{textDocumentSync:1,documentSymbolProvider:true,hoverProvider:true},serverInfo:{name:'Nova',version:'0.1'}});if(method==='initialized')return;if(method==='shutdown')return response(id,null);if(method==='exit')return process.exit(0);if(method==='textDocument/didOpen'){documents.set(params.textDocument.uri,params.textDocument.text);notify('textDocument/publishDiagnostics',{uri:params.textDocument.uri,diagnostics:diagnostics(params.textDocument.uri,params.textDocument.text)});return;}if(method==='textDocument/didChange'){const text=params.contentChanges?.at(-1)?.text??documents.get(params.textDocument.uri)??'';documents.set(params.textDocument.uri,text);notify('textDocument/publishDiagnostics',{uri:params.textDocument.uri,diagnostics:diagnostics(params.textDocument.uri,text)});return;}if(method==='textDocument/diagnostic'){const uri=params.textDocument.uri;const text=params.text??documents.get(uri)??'';return response(id,diagnostics(uri,text));}if(method==='textDocument/documentSymbol'){const uri=params.textDocument.uri;const text=params.text??documents.get(uri)??'';return response(id,symbols(uri,text));}if(method==='textDocument/hover'){const uri=params.textDocument.uri;const text=documents.get(uri)??params.text??'';const result=analyzeContracts(text,{file:uri});return response(id,{contents:{kind:'markdown',value:`Nova: ${Object.keys(result.functions).length} functions, ${result.diagnostics.length} diagnostics`}});}if(id!==undefined)return response(id,null);}
